# Generated by Django 5.0.4 on 2024-04-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTextModel',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('random_subject', models.CharField(max_length=50)),
                ('random_text', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'tests',
            },
        ),
    ]
