# Generated by Django 5.0.4 on 2024-04-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itemreview_review_items_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmaterial',
            options={'ordering': ['title'], 'verbose_name': 'Матеріал', 'verbose_name_plural': 'Матеріали'},
        ),
    ]
