# Generated by Django 5.0.4 on 2024-04-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itemcategory_itemcollection_itemcolour_itemmaterial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='upholstery_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Щільність набивки'),
        ),
        migrations.AlterField(
            model_name='items',
            name='upholstery_material',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наповнення'),
        ),
    ]
