# Use an official Nginx image
FROM nginx:latest

# Remove the default configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# The SSL certificates are mounted as volumes
# No need to COPY them inside the Dockerfile

# Expose port 80 and 443
EXPOSE 80
EXPOSE 443
