# Use an Nginx base image
FROM nginx:alpine

# Copy Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose ports
EXPOSE 80 443

# Command to start Nginx
CMD ["nginx", "-g", "daemon off;"]
