version: '3'

services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_app

volumes:
  postgres_data:
