services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django_app
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./privkey.pem:/etc/ssl/private/privkey.pem:ro

volumes:
  postgres_data:

