# Generated by Django 5.0.4 on 2024-05-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_rename_category_items_item_category'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Код замовлення')),
                ('hard_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemhardbody', verbose_name='Корпус')),
                ('related_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items', verbose_name='Товар')),
                ('related_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordertotal', verbose_name='Замовлення')),
                ('soft_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemsoftbody', verbose_name='Оздоблення')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'db_table': 'order_item',
                'ordering': ['related_order'],
            },
        ),
    ]
