# Generated by Django 5.0.4 on 2024-06-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orderitem_ordercart_alter_ordercart_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercart',
            old_name='hard_item',
            new_name='hard_body',
        ),
        migrations.RenameField(
            model_name='ordercart',
            old_name='soft_item',
            new_name='soft_body',
        ),
    ]
