# Generated by Django 5.0.4 on 2024-06-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_hard_item_ordercart_hard_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertotal',
            name='items',
            field=models.JSONField(default=None, verbose_name='Товари'),
        ),
        migrations.AddField(
            model_name='ordertotal',
            name='order_sum',
            field=models.FloatField(default=None, verbose_name='Сума'),
        ),
        migrations.AddField(
            model_name='ordertotal',
            name='payment_type',
            field=models.CharField(default='Готівка', max_length=50, verbose_name='Тип оплати'),
        ),
        migrations.AddField(
            model_name='ordertotal',
            name='phone_number',
            field=models.CharField(default=0, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='ordertotal',
            name='promocode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='ordertotal',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення'),
        ),
        migrations.AlterField(
            model_name='ordertotal',
            name='order_number',
            field=models.IntegerField(verbose_name='Код'),
        ),
    ]
