# Generated by Django 5.0.4 on 2024-06-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordertotal_area_ordertotal_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertotal',
            name='area',
        ),
        migrations.RemoveField(
            model_name='ordertotal',
            name='location_type',
        ),
        migrations.AlterField(
            model_name='ordertotal',
            name='location',
            field=models.CharField(default=None, verbose_name='Населений пункт'),
        ),
    ]
