# Generated by Django 5.0.4 on 2024-06-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_ordertotal_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercart',
            options={'ordering': ['related_user'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзини'},
        ),
    ]
