# Generated by Django 5.0.4 on 2024-05-09 10:37

import django.db.models.deletion
import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Виробник')),
                ('about', models.TextField(blank=True, verbose_name='Інформація')),
            ],
            options={
                'verbose_name': 'Виробник',
                'verbose_name_plural': 'Виробники',
                'db_table': 'item_manufacturer',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ItemMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=50, verbose_name='Тип матеріалу')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Виробник матеріалу')),
                ('title', models.CharField(max_length=150, verbose_name='Назва матеріалу')),
                ('colour', models.CharField(max_length=50, verbose_name='Колір матеріалу')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Семпл кольору')),
            ],
            options={
                'verbose_name': 'Матеріали',
                'verbose_name_plural': 'Матеріали',
                'db_table': 'item_materials',
                'ordering': ['material_type', 'manufacturer', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ItemRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Тип кімнати')),
            ],
            options={
                'verbose_name': 'Тип кімнати',
                'verbose_name_plural': 'Типи кімнат',
                'db_table': 'item_room_type',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ItemCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Колекція')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.itemmanufacturer', verbose_name='Виробник')),
            ],
            options={
                'verbose_name': 'Колекція',
                'verbose_name_plural': 'Колекції',
                'db_table': 'item_collection',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Категорія')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.itemroomtype', verbose_name='Тип кімнати')),
            ],
            options={
                'verbose_name': "Категорія об'єкта",
                'verbose_name_plural': "Категорії об'єкта",
                'db_table': 'item_category',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('price', models.FloatField(verbose_name='Ціна')),
                ('article_code', models.IntegerField(unique=True, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('colour', models.CharField(blank=True, max_length=150, verbose_name='Колір')),
                ('availability', models.BooleanField(default=True, verbose_name='В наявності')),
                ('in_stock', models.IntegerField(default=1, verbose_name='На складі')),
                ('length', models.IntegerField(blank=True, verbose_name='Довжина')),
                ('width', models.IntegerField(blank=True, verbose_name='Висота')),
                ('height', models.IntegerField(blank=True, verbose_name='Висота')),
                ('form', models.CharField(max_length=50, verbose_name='Форма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Відредаговано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Статус')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemcollection', verbose_name='Колекція')),
                ('item_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemcategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'db_table': 'item_items',
                'ordering': ['item_category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('second_name', models.CharField(max_length=150, verbose_name='Прізвище')),
                ('review', models.TextField(blank=True, verbose_name='Відгук')),
                ('rating', models.IntegerField(validators=[items.models.validate_even], verbose_name='Оцінка товару')),
                ('review_usefulness_counter', models.IntegerField(default=0, verbose_name='Корисність відгуку')),
                ('related_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'db_table': 'item_review',
                'ordering': ['related_item'],
            },
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото товару')),
                ('related_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='items.items', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'db_table': 'item_photo',
                'ordering': ['related_item'],
            },
        ),
        migrations.CreateModel(
            name='ItemHardBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_material', to='items.itemmaterials', verbose_name='Корпус')),
                ('facade_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facade_material', to='items.itemmaterials', verbose_name='Фасад')),
                ('tabletop_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabletop_material', to='items.itemmaterials', verbose_name='Стільниця')),
                ('related_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуси',
                'db_table': 'item_hard_body',
                'ordering': ['related_item'],
            },
        ),
        migrations.CreateModel(
            name='ItemSoftBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_place', models.CharField(max_length=100, verbose_name='Спальне місце')),
                ('sleep_size', models.CharField(max_length=100, verbose_name='Спальне місце ДхШ')),
                ('springs_type', models.CharField(max_length=100, verbose_name='Пружини')),
                ('linen_niche', models.BooleanField(verbose_name='Ніша д.білизни')),
                ('mechanism', models.CharField(max_length=100, verbose_name='Механізм')),
                ('filler', models.CharField(max_length=100, verbose_name='Наповнення')),
                ('counter_claw', models.BooleanField(verbose_name='Антикіготь')),
                ('armrests', models.CharField(max_length=100, verbose_name='Підлокітники')),
                ('max_weight', models.IntegerField(verbose_name='Макс. навантаження')),
                ('other', models.CharField(max_length=150, verbose_name='Інше')),
                ('related_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items', verbose_name='Товар')),
                ('upholstery_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemmaterials', verbose_name='Оббивка')),
            ],
            options={
                'verbose_name': "М'який матеріал",
                'verbose_name_plural': "М'які матеріали",
                'db_table': 'item_soft_body',
                'ordering': ['related_item'],
            },
        ),
    ]
