# Generated by Django 5.0.4 on 2024-05-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_itemphoto_related_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemphoto',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
