# Generated by Django 5.0.4 on 2024-05-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20240506_1703'),
    ]

    operations = [
    ]
