# Generated by Django 5.0.4 on 2024-05-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemphoto_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото товару'),
        ),
    ]
