# Generated by Django 5.0.4 on 2024-05-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_itemphoto_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemphoto',
            name='file_path',
        ),
        migrations.AlterField(
            model_name='itemphoto',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото товару'),
        ),
    ]
