# Generated by Django 5.0.4 on 2024-05-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_itemphoto_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='photo',
            field=models.ImageField(upload_to='items/<django.db.models.fields.related.ForeignKey>/', verbose_name='Фото товару'),
        ),
    ]
