# Generated by Django 5.0.4 on 2024-05-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_itemphoto_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemphoto',
            name='file_path',
        ),
    ]
