# Generated by Django 5.0.4 on 2024-05-12 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_itemphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото товару'),
        ),
        migrations.AlterField(
            model_name='itemphoto',
            name='related_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='items.items', verbose_name='Товар'),
        ),
    ]
