# Generated by Django 5.0.4 on 2024-05-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_itemphoto_photo_alter_itemphoto_related_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='related_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items', verbose_name='Товар'),
        ),
    ]
