# Generated by Django 5.0.4 on 2024-05-13 12:30

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_itemphoto_related_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to=items.models.ItemPhoto.item_photo_upload_path, verbose_name='Фото товару'),
        ),
    ]
