# Generated by Django 5.0.4 on 2024-05-15 16:14

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_itemphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaterials',
            name='photo',
            field=models.ImageField(blank=True, upload_to=items.models.ItemMaterials.item_material_upload_path, verbose_name='Семпл кольору'),
        ),
    ]
