# Generated by Django 5.0.4 on 2024-05-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_itemmaterials_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsoftbody',
            name='counter_claw',
            field=models.CharField(verbose_name='Антикіготь'),
        ),
        migrations.AlterField(
            model_name='itemsoftbody',
            name='linen_niche',
            field=models.CharField(verbose_name='Ніша д.білизни'),
        ),
    ]
