# Generated by Django 5.0.4 on 2024-05-16 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_alter_itemsoftbody_armrests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.IntegerField(verbose_name='Знижка, %')),
                ('related_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Знижка',
                'verbose_name_plural': 'Знижка',
                'db_table': 'item_discount',
                'ordering': ['related_item'],
            },
        ),
    ]
