# Generated by Django 5.0.4 on 2024-05-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_itemdiscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemreview',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
