# Generated by Django 5.0.4 on 2024-05-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_rename_second_name_itemreview_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreview',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Відгук'),
        ),
    ]
