# Generated by Django 5.0.4 on 2024-05-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_alter_itemreview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='sold',
            field=models.IntegerField(default=0, verbose_name='Продано одиниць'),
        ),
    ]
