# Generated by Django 5.0.4 on 2024-05-17 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_items_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdiscount',
            name='related_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='items.items', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='itemhardbody',
            name='related_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hard_body', to='items.items', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='itemphoto',
            name='related_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='items.items', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='related_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='items.items', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='itemsoftbody',
            name='related_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_body', to='items.items', verbose_name='Товар'),
        ),
    ]
