# Generated by Django 5.0.4 on 2024-05-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_alter_itemdiscount_related_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_category',
            new_name='category',
        ),
    ]
