# Generated by Django 5.0.4 on 2024-05-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_rename_item_category_items_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='category',
            new_name='item_category',
        ),
    ]
