# Generated by Django 5.0.4 on 2024-06-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_rename_category_items_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='search_tags',
            field=models.TextField(null=True, verbose_name='Ключові слова'),
        ),
    ]
