# Generated by Django 5.0.4 on 2024-05-31 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_rename_category_items_item_category'),
        ('users', '0002_alter_userbio_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavorites',
            unique_together={('related_user', 'related_item')},
        ),
    ]
