# Generated by Django 5.0.4 on 2024-06-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userbio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavorites',
            options={'ordering': ['related_user'], 'verbose_name': 'Обране користувача', 'verbose_name_plural': 'Обрані користувачів'},
        ),
    ]
