# name: EC2 Python APP

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main_branch1", "main_branch2" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install build-essential and python3.10-dev
        run: |
          sudo apt-get install build-essential python3.10-dev -y

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 --exclude=venv/ --count --select=E9,F63,F7,F82 --show-source --statistics

          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 --exclude=venv/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        shell: bash

      # - name: Test with pytest
      #   run: |
      #     cd backend
      #     DJANGO_SETTINGS_MODULE=backend.settings pytest
      #   shell: bash


  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: List files in repository
        run: ls -al

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}

      - name: Build and push Django app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.django
          push: true
          tags: artmtsh/store_backend:latest

      - name: Build and push Nginx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.nginx
          push: true
          tags: artmtsh/store_nginx:latest

  deploy:
    runs-on: self-hosted
    needs: docker
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: List files in repository
        run: ls -al

      - name: Stop and remove containers and images (if any)
        run: |
          docker stop $(docker ps -a -q) || true
          docker remove $(docker ps -a -q) || true
          docker rmi -f $(docker images -aq) || true
        continue-on-error: true

#      - name: Pull latest image from Docker Hub
#        run: docker pull artmtsh/store_backend:latest
#
#      - name: Run new container
#        run: docker run -d -p 8000:8000 --name store_backend_container artmtsh/store_backend:latest

      - name: Build Django container
        run: |
          docker build -t store_backend:latest -f Dockerfile.django .

      - name: Run Django container
        run: |
          docker run -d --name django_app -p 8000:8000 store_backend:latest

      - name: Build Nginx container
        run: |
          docker build -t store_nginx:latest -f Dockerfile.nginx .

      - name: Run Nginx container
        run: |
          docker run -d --name nginx -p 80:80 -p 443:443 \
          --link django_app:django_app \
          -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro \
          -v $(pwd)/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro \
          -v $(pwd)/privkey.pem:/etc/ssl/private/privkey.pem:ro \
          store_nginx:latest
