# name: EC2 Python APP

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main_branch1", "main_branch2" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install build-essential and python3.10-dev
        run: |
          sudo apt-get install build-essential python3.10-dev -y

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 --exclude=venv/ --count --select=E9,F63,F7,F82 --show-source --statistics

          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 --exclude=venv/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        shell: bash

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # - name: Test with pytest
      #   run: |
      #     cd backend
      #     DJANGO_SETTINGS_MODULE=backend.settings pytest
      #   shell: bash


  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: artmtsh/store_backend:latest

  deploy:
    runs-on: self-hosted
    needs: docker
    steps:

      - name: Stop and remove containers and images (if any)
        run: |
          docker stop $(docker ps -a -q) || true
          docker remove $(docker ps -a -q) || true
          docker rmi -f $(docker images -aq) || true
        continue-on-error: true


      - name: Pull latest image from Docker Hub
        run: docker pull artmtsh/store_backend:latest

#      - name: Run new container
#        run: docker run -d -p 80:80 --name store_backend_container artmtsh/store_backend:latest

      - name: List directory contents
        run: ls -la

      - name: Deploy with Docker Compose
        run: |
          cat <<EOF > docker-compose.yml
          version: '3'

          services:
            web:
              image: artmtsh/store_backend:latest
              expose:
                - "8000"
              networks:
                - mynetwork

            nginx:
              image: nginx:alpine
              ports:
                - "80:80"
                - "443:443"
              volumes:
                - app/etc/nginx/nginx.conf:app/etc/nginx/nginx.conf
                - app/etc/nginx/certs:app/etc/nginx/certs
              depends_on:
                - web
              networks:
                - mynetwork

          networks:
            mynetwork:

          EOF
          docker-compose up -d
