# name: EC2 Python APP

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main_branch1", "main_branch2" ]

permissions:
  contents: read



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Django backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          dockerfile: Dockerfile
          push: true
          tags: artmtsh/store_backend:latest

      - name: Build and push Nginx image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          dockerfile: Dockerfile
          push: true
          tags: artmtsh/nginx_backend:latest

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull artmtsh/store_backend:latest
            docker pull artmtsh/nginx_backend:latest
            docker run -d -p 8000:8000 --name store_backend_container artmtsh/store_backend:latest
            docker run -d -p 80:80 -p 443:443 --name nginx_container --link store_backend_container:web artmtsh/nginx_backend:latest